# -*- coding: utf-8 -*-
"""Covid19-Analysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17dXjfWkVqHkAbZboLprHZGMvL5p-Y8GU

import required modules
"""

import streamlit as st
import pandas as pd
import seaborn as sns

"""Read & edit Covid-19 dataset"""

@st.cache
def covid():
    covid = pd.read_csv("time_series_covid19_confirmed_global.csv")
    covid_agg = covid.groupby("Country/Region").sum()
    covid_agg.drop(['Lat', 'Long'], axis=1, inplace=True)
    covid_agg['Average cases'] = covid_agg.mean(axis=1)
    covid_agg.loc['Average cases'] = covid_agg.mean()
    covid_data = pd.DataFrame(covid_agg['Average cases'])
    return covid_data

"""Read & edit Population dataset"""

def pop():
    pop = pd.read_csv("WPP2019_TotalPopulationBySex.csv")
    pop_agg = pop.groupby("Location").sum()
    useless_cols = ['LocID', 'VarID', 'Time', 'PopMale', 'PopFemale', 'MidPeriod', 'PopTotal']
    pop_agg.drop(useless_cols, axis=1, inplace=True)
    pop_agg.rename(columns={'PopDensity': 'Population Density'}, inplace=True)
    return pop_agg

"""Read & edit Temperature dataset"""

@st.cache
def temp():
    temp = pd.read_csv("globallandtemperaturesbymajorcity.csv")
    temp_agg = temp.groupby("country").sum()
    temp_agg.drop(['averagetemperatureuncertainty'], axis=1, inplace=True)
    temp_agg.rename(columns={'averagetemperature': 'Average Temperature'}, inplace=True)
    return temp_agg

"""Join the three datasets to create a new dataframe"""

data0 = covid().join(pop(), how='inner')
data1 = data0.join(temp(), how='inner')

"""Creation of Streamlit pages, adding texts & widgets, plotting graph using seaborn and displaying dataframe"""

def main():
    page = st.sidebar.selectbox("Choose a page", ['Analysis', 'About'])
    if page == "Analysis":
        st.title("""Covid-19 Analysis
                     Based on global climate and population""")
        parameter = st.selectbox(
        "Choose a parameter", list(data1.columns.values[1:]))

        x = data1['Average cases']
        y = data1[parameter]
        sns.regplot(x, y)
        st.pyplot()

        if st.checkbox('Show Dataframe'):
            display = pd.DataFrame(data1)
            display[['Average cases', parameter]]

    elif page == 'About':
        st.title("About")
        st.subheader('Author')
        st.write('This project was created by Asma Khan.')
        st.subheader('Datasets')
        st.write("Following provides the sources of datasets used in this project:")
        st.write("[Covid-19 dataset](https://data.humdata.org/dataset/novel-coronavirus-2019-ncov-cases)")
        st.write("[Global Population dataset](https://population.un.org/wpp/Download/Standard/CSV/)")
        st.write("[Temperature dataset](https://datacatalog.worldbank.org/dataset/climate-change-knowledge-portal-historical-data)")
        st.subheader('Source code')
        st.write('https://github.com/Asma-0101/Covid19-Analysis')


if __name__ == '__main__':
    main()